### ISSUE TITLE
min_Qf_perc

### ISSUE THREAD

**Issue by SebastianGnann** [TOSSHtoolbox/TOSSH#2]
Currently, min_Qf_perc is calculated as follows:
`min_Qf_perc = 100*(min(event_array(i,7)./event_array(i,1)));`

It seems like it only takes the i-th event, i.e. the last one, to calculate min_Qf_perc.

Shouldn't it be something like:
`min_Qf_perc = 100*(min(event_array(:,7)./event_array(:,1)));` ?

**Comment by mcmillanhk** [comment]
Yes, fixed this. I wonder if it's almost always going to return 0 now, but that is more a problem with the signature definition.
